### ISSUE TITLE
Extraction of event logs

### ISSUE THREAD

**Issue by christbryan** [process-analytics/bpmn-layout-generators#107]
Hello Bonitasoft Team,

I have executted my process several time and I would like to extract my event logs for process analytics but don't know how to. Could you give a step by step guide? Please

**Comment by tbouffard** [comment]
from https://github.com/process-analytics/bpmn-visualization-R/issues/175#issuecomment-1367367194
> Okay thanks for the answer.
But I would like to send my event log through the process analytics form
for my event log to be analyzed but don't know how to get my event logs.
Any help will be appreciated please.
Thanks

Thanks for your interest in the Model Generation Application. I guess you are talking about https://process-analytics.dev/model-generation-application/

Did you check the proposed solutions you received in the Bonita Community Q&A: https://community.bonitasoft.com/node/38001#node-38039
- Submitted by nour.assy@bonit... on Tue, 12/20/2022 - 16:09: event handlers, which is a "push" solution. The pushed data must be handled externally
- Submitted by romain.bioteau on Thu, 12/29/2022 - 15:32: use Bonita Rest API to pull data and store them in an external storage. Then query the storage to get the data and generate the XES file.

Generating the event logs is out of the topic of the bpmn-layout-generators project, especially when it first involves extracting data from a dedicated vendor (Bonita in your case). You will find more information and answers in the Bonita Community Q&A.

**Comment by tbouffard** [comment]
No answer here, the issue seems solved according to https://community.bonitasoft.com/node/38001#node-38039
So closing.
